name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          auto-update-conda: true
          activate-environment: toikka2025label
      - name: Install pre-commit hooks
        shell: bash -l {0}
        run: pre-commit install --install-hooks
      - name: Run pre-commit against all files
        shell: bash -l {0}
        run: pre-commit run --all-files --show-diff-on-failure
